version: '2'

services:
  web:
    build: .
    image: hostview/web
    ports:
     - "1337:1337"
    links:
     - redis
    networks:
      - backtier
    environment:
     NODE_ENV: production
     HOSTVIEW_REDIS: redis://redis:6379
     HOSTVIEW_DB:

  redis:
    image: redis:3.0
    networks:
      - backtier

networks:
  backtier:
    driver: bridge