version: '2'

services:
  web:
    build: .
    image: hostview/web
    volumes:
     - ./app:/app
     - /app/node_modules
    links:
     - redis
    networks:
      - backtier
    environment:
     NODE_ENV: producation
     DEBUG: hostview
     HOSTVIEW_REDIS: redis://redis:6379
     HOSTVIEW_DB:

  redis:
    image: redis:3.0
    networks:
      - backtier

networks:
  backtier:
    driver: bridge